IMAGE_SUPPORTS_BMP=1
IMAGE_SUPPORTS_FITS=1
IMAGE_SUPPORTS_JPEG=1
IMAGE_SUPPORTS_PNG=1
IMAGE_SUPPORTS_PPM=1
IMAGE_SUPPORTS_TGA=1
IMAGE_SUPPORTS_TIFF=1

ifdef IMAGE_SUPPORTS_BMP
MACROS+=IMAGE_SUPPORTS_BMP
endif
ifdef IMAGE_SUPPORTS_FITS
MACROS+=IMAGE_SUPPORTS_FITS
endif
ifdef IMAGE_SUPPORTS_JPEG
MACROS+=IMAGE_SUPPORTS_JPEG
endif
ifdef IMAGE_SUPPORTS_PNG
MACROS+=IMAGE_SUPPORTS_PNG
endif
ifdef IMAGE_SUPPORTS_PPM
MACROS+=IMAGE_SUPPORTS_PPM
endif
ifdef IMAGE_SUPPORTS_TGA
MACROS+=IMAGE_SUPPORTS_TGA
endif
ifdef IMAGE_SUPPORTS_TIFF
MACROS+=IMAGE_SUPPORTS_TIFF
endif
