DIST_FILENAME=Image
DIST_TYPE=lib

include ../Common/Base.mk
include ../Tensor/Include.mk
include Config.mk

ifdef IMAGE_SUPPORT_BMP
MACROS+=SUPPORT_BMP
endif
ifdef IMAGE_SUPPORT_FITS
MACROS+=SUPPORT_FITS
endif
ifdef IMAGE_SUPPORT_JPEG
MACROS+=SUPPORT_JPEG
endif
ifdef IMAGE_SUPPORT_PNG
MACROS+=SUPPORT_PNG
endif
ifdef IMAGE_SUPPORT_PPM
MACROS+=SUPPORT_PPM
endif
ifdef IMAGE_SUPPORT_TGA
MACROS+=SUPPORT_TGA
endif
ifdef IMAGE_SUPPORT_TIFF
MACROS+=SUPPORT_TIFF
endif
