DIST_FILENAME=Image
DIST_TYPE=lib

include ../Common/Base.mk
include ../Tensor/Include.mk
include Config.mk

ifdef IMAGE_SUPPORT_BMP
MACROS+=IMAGE_SUPPORTS_BMP
endif
ifdef IMAGE_SUPPORT_FITS
MACROS+=IMAGE_SUPPORTS_FITS
endif
ifdef IMAGE_SUPPORT_JPEG
MACROS+=IMAGE_SUPPORTS_JPEG
endif
ifdef IMAGE_SUPPORT_PNG
MACROS+=IMAGE_SUPPORTS_PNG
endif
ifdef IMAGE_SUPPORT_PPM
MACROS+=IMAGE_SUPPORTS_PPM
endif
ifdef IMAGE_SUPPORT_TGA
MACROS+=IMAGE_SUPPORTS_TGA
endif
ifdef IMAGE_SUPPORT_TIFF
MACROS+=IMAGE_SUPPORTS_TIFF
endif
