DIST_FILENAME=ImageLua
DIST_TYPE=lib
include ../../Common/Base.mk
include ../../Common/Include.mk
include ../../Tensor/Include.mk
include ../Include.mk
include ../../LuaCxx/Include.mk		# only for the lua link and include paths
